# permissions for end users to view apps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-viewer-role
rules:
- apiGroups:
  - ingress.wukong.com
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.wukong.com
  resources:
  - apps/status
  verbs:
  - get
